"""Core sitemap generation logic. No CLI dependencies."""

import gzip
import logging
from pathlib import Path

from lxml import etree

from seo_bhishma.models.common import ProgressCallback
from seo_bhishma.models.sitemap_generator import UrlEntry

logger = logging.getLogger(__name__)

SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"
IMAGE_NS = "http://www.google.com/schemas/sitemap-image/1.1"
NEWS_NS = "http://www.google.com/schemas/sitemap-news/0.9"


def _coerce_entries(urls: list[str] | list[UrlEntry]) -> list[UrlEntry]:
    """Accept either raw URL strings or full ``UrlEntry`` objects."""
    out: list[UrlEntry] = []
    for u in urls:
        if isinstance(u, UrlEntry):
            out.append(u)
        elif isinstance(u, str):
            out.append(UrlEntry(loc=u))
        elif isinstance(u, dict):
            out.append(UrlEntry(**u))
        else:
            raise TypeError(f"Unsupported URL type: {type(u)}")
    return out


def generate_sitemap(
    urls: list[str] | list[UrlEntry],
    priority: str | None = None,
    frequency: str | None = None,
    lastmod: str | None = None,
    stylesheet: str | None = None,
) -> bytes:
    """Generate a sitemap XML document.

    Args:
        urls: List of URL strings or ``UrlEntry`` objects. ``UrlEntry`` fields
            override the generator defaults below for that URL.
        priority: Default priority value (e.g. ``"0.8"``).
        frequency: Default change frequency (e.g. ``"daily"``).
        lastmod: Default last modified date (ISO 8601).
        stylesheet: Optional XSL stylesheet URL.

    Returns:
        XML content as bytes.
    """
    entries = _coerce_entries(urls)
    has_images = any(e.images for e in entries)
    has_news = any(e.news for e in entries)

    nsmap = {None: SITEMAP_NS}
    if has_images:
        nsmap["image"] = IMAGE_NS
    if has_news:
        nsmap["news"] = NEWS_NS

    urlset = etree.Element("urlset", nsmap=nsmap)
    urlset.append(etree.Comment("Generated by seo-bhishma"))

    for entry in entries:
        url_element = etree.SubElement(urlset, "url")
        etree.SubElement(url_element, "loc").text = entry.loc

        effective_lastmod = entry.lastmod or lastmod
        effective_priority = entry.priority or priority
        effective_freq = entry.changefreq or frequency

        if effective_lastmod:
            etree.SubElement(url_element, "lastmod").text = effective_lastmod
        if effective_freq:
            etree.SubElement(url_element, "changefreq").text = effective_freq
        if effective_priority:
            etree.SubElement(url_element, "priority").text = effective_priority

        for img in entry.images:
            img_el = etree.SubElement(url_element, f"{{{IMAGE_NS}}}image")
            etree.SubElement(img_el, f"{{{IMAGE_NS}}}loc").text = img.loc
            if img.caption:
                etree.SubElement(img_el, f"{{{IMAGE_NS}}}caption").text = img.caption
            if img.title:
                etree.SubElement(img_el, f"{{{IMAGE_NS}}}title").text = img.title

        for news in entry.news:
            news_el = etree.SubElement(url_element, f"{{{NEWS_NS}}}news")
            pub_el = etree.SubElement(news_el, f"{{{NEWS_NS}}}publication")
            etree.SubElement(pub_el, f"{{{NEWS_NS}}}name").text = news.publication_name
            etree.SubElement(pub_el, f"{{{NEWS_NS}}}language").text = news.publication_language
            if news.publication_date:
                etree.SubElement(news_el, f"{{{NEWS_NS}}}publication_date").text = news.publication_date
            etree.SubElement(news_el, f"{{{NEWS_NS}}}title").text = news.title

    xml = etree.tostring(urlset, pretty_print=True, xml_declaration=True, encoding="UTF-8")
    if stylesheet:
        # Inject stylesheet PI after the XML declaration
        decl, _, rest = xml.partition(b"?>")
        xml = decl + b"?>\n<?xml-stylesheet type=\"text/xsl\" href=\"" + stylesheet.encode() + b"\"?>" + rest
    return xml


def generate_sitemap_index(sitemap_locs: list[str]) -> bytes:
    """Generate a sitemap index XML document.

    Args:
        sitemap_locs: List of sitemap file URLs/paths.

    Returns:
        XML content as bytes.
    """
    sitemapindex = etree.Element("sitemapindex", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
    comment = etree.Comment("Generated by seo-bhishma")
    sitemapindex.append(comment)

    for loc_text in sitemap_locs:
        sitemap_el = etree.SubElement(sitemapindex, "sitemap")
        loc_el = etree.SubElement(sitemap_el, "loc")
        loc_el.text = loc_text

    return etree.tostring(sitemapindex, pretty_print=True, xml_declaration=True, encoding="UTF-8")


def write_sitemap(file_path: str, content: bytes, compressed: bool = False) -> None:
    """Write sitemap content to a file.

    Args:
        file_path: Destination file path.
        content: XML bytes to write.
        compressed: If True, gzip the output.
    """
    try:
        if compressed:
            with gzip.open(file_path, "wb") as f:
                f.write(content)
        else:
            with open(file_path, "wb") as f:
                f.write(content)
    except Exception as e:
        logger.error("Failed to write sitemap to %s: %s", file_path, e)
        raise


def generate_nested_sitemaps(
    urls: list[str] | list[UrlEntry],
    output_dir: str,
    url_limit: int = 50000,
    priority: str | None = None,
    frequency: str | None = None,
    lastmod: str | None = None,
    compressed: bool = False,
    on_progress: ProgressCallback | None = None,
) -> tuple[list[str], str]:
    """Generate nested sitemaps with a sitemap index.

    Args:
        urls: All URLs to include across sitemaps.
        output_dir: Directory to write sitemap files.
        url_limit: Maximum URLs per individual sitemap.
        priority: Optional priority for all URLs.
        frequency: Optional change frequency.
        lastmod: Optional last modified date.
        compressed: If True, gzip all output files.
        on_progress: Optional progress callback.

    Returns:
        Tuple of (list of sitemap file paths, sitemap index file path).
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    sitemap_files: list[str] = []
    total_chunks = (len(urls) + url_limit - 1) // url_limit

    for i in range(0, len(urls), url_limit):
        chunk = urls[i : i + url_limit]
        content = generate_sitemap(chunk, priority, frequency, lastmod)

        filename = f"sitemap_{i // url_limit}.xml"
        if compressed:
            filename += ".gz"

        file_path = str(output_path / filename)
        write_sitemap(file_path, content, compressed)
        sitemap_files.append(file_path)

        if on_progress:
            on_progress(len(sitemap_files), total_chunks)

    # Generate index
    index_content = generate_sitemap_index(sitemap_files)
    index_filename = "sitemap_index.xml"
    if compressed:
        index_filename += ".gz"
    index_path = str(output_path / index_filename)
    write_sitemap(index_path, index_content, compressed)

    return sitemap_files, index_path
